on:
  push:
    tags:
    - "v*"

name: Release

permissions:
  contents: write

jobs:
  release-xelatex:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6
        name: checkout code
      - uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: |
            apk add zip diffutils
            tlmgr update --self
            tlmgr update l3build
            make build-dev
        name: build package with XeLaTeX
      - uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: .github/ci/build_all_variants.sh -halt-on-error -time -quiet -xelatex
        name: build all variants with XeLaTeX
      - uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: |
            apk add font-noto-cjk
            .github/ci/gen_cover.sh -halt-on-error -time -quiet -xelatex
            mv build/cover.pdf build/sample-all-covers.pdf
        name: build cover with XeLaTeX
      - run: cat build/*.log
        name: display build log
        if: ${{ failure() || success() }}
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: true
          prerelease: false
          files: |
            build/sjtulib-talk-maxplus-blue.pdf
            build/sjtulib-talk-maxplus-red.pdf
            build/sjtulib-talk-max-red.pdf
            build/sjtulib-talk-min-red.pdf
            build/sample-all-covers.pdf
            src/sjtubeamer-ctan.zip
            sjtubeamer-online.zip
            src/build/distrib/ctan/sjtubeamer/sjtubeamerdevguide.pdf
            src/build/distrib/ctan/sjtubeamer/sjtubeamer.pdf
            src/build/distrib/ctan/sjtubeamer/sjtubeamerquickstart.pdf
